# theme: jekyll-theme-architect
remote_theme: just-the-docs/just-the-docs
title: Buddy Compiler
description: Domain Specific Compiler Infrastructure
markdown: kramdown
url: "https://buddy-compiler.github.io"
sidebar: true
color_scheme: buddy
