# theme: jekyll-theme-architect
remote_theme: zhanghb97/just-the-docs
title: Buddy Compiler
description: Domain Specific Compiler Infrastructure
markdown: kramdown
url: "https://buddycompiler.com"
baseurl: ""
sidebar: true
color_scheme: buddy
logo: "./Resources/buddy-compiler-logo.png"
nav:
  - title: "Home"
    url:   /
  - title: "Benchmarks"
    url:   /benchmarks/
  - title: "Insights"
    url:   /insights/
